title: A Story From Down Under
author: jonathanbraude1
email: jonathanbraude1@github.com
description: > # this means to ignore newlines until "baseurl:"
  This is where I will tell the world my story

# social links
twitter_username: N/A
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
